name = "otlpflare2"
main = "build/worker/shim.mjs"
compatibility_date = "2024-01-01"

[build]
command = "cargo install -q worker-build && worker-build --release"

[vars]
PIPELINE_LOGS = "https://5d98d4fca15747fa95fde8305e78b541.ingest.cloudflare.com"
PIPELINE_TRACES = "https://b356ff43675744afb858da25ec7e1452.ingest.cloudflare.com"
PIPELINE_GAUGE = "https://bd9571770daa4bf3ae43edecaf13fe24.ingest.cloudflare.com"
PIPELINE_SUM = "https://afd81f6702d14e93865cad88e4aba0a9.ingest.cloudflare.com"

[observability]
enabled = true

[observability.logs]
invocation_logs = true
head_sampling_rate = 0.1

[observability.traces]
enabled = false
